services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: idec-mails:latest
    container_name: idec-mails
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - BODY_SIZE_LIMIT=5242880
    networks:
      - coolify
      - mailu_default
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.routers.http-0-idec.entryPoints=http
      - traefik.http.routers.http-0-idec.middlewares=redirect-to-https
      - traefik.http.routers.http-0-idec.rule=Host(`mail.idec.ec`)
      - traefik.http.routers.http-0-idec.service=http-0-idec
      - traefik.http.routers.https-0-idec.entryPoints=https
      - traefik.http.routers.https-0-idec.middlewares=gzip
      - traefik.http.routers.https-0-idec.rule=Host(`mail.idec.ec`)
      - traefik.http.routers.https-0-idec.service=https-0-idec
      - traefik.http.routers.https-0-idec.tls=true
      - traefik.http.routers.https-0-idec.tls.certresolver=letsencrypt
      - traefik.http.services.http-0-idec.loadbalancer.server.port=3000
      - traefik.http.services.https-0-idec.loadbalancer.server.port=3000

networks:
  coolify:
    external: true
  mailu_default:
    external: true